/*
 *  Copyright 2010 Emmanuel Astier & Kevin Gaudin
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.acra;

import android.app.Application;
import android.net.Uri;

/**
 * <p>
 * Base class for any application which need to send crash reports. The final
 * application has to extend this class and at least implement the abstract
 * method {@link #getFormId()} by returning a valid GoogleDocs Form id string
 * generated by importing ACRA's specific spreadsheet template.
 * </p>
 * <p>
 * If you prefer sending crash reports to your own script on your own server,
 * you can override {@link #getFormUri()} and return any Url string to your
 * sever script (like : "http://www.myserver.com/myscript.php").
 * </p>
 */
public abstract class CrashReportingApplication extends Application {
    protected static final String LOG_TAG = "CrashReport";

    /*
     * (non-Javadoc)
     * 
     * @see android.app.Application#onCreate()
     */
    @Override
    public void onCreate() {
        super.onCreate();
        ErrorReporter.getInstance().setFormUri(getFormUri());
        ErrorReporter.getInstance().init(getApplicationContext());
        ErrorReporter.getInstance()
                .checkAndSendReports(getApplicationContext());
    }

    /**
     * <p>Override this method to send the crash reports to your own server script.
     * Your script will have to get HTTP POST request parameters named as described
     * in {@link ErrorReporter} source code (*_KEY fields values).</p>
     * <p>If you override this method with your own url, your implementation of
     * the abstract {@link #getFormId()} can be empy as it will not be called
     * by any other method or object.</p>
     * @return A String containing the Url of your custom server script.
     */
    public Uri getFormUri() {
        return Uri.parse("http://spreadsheets.google.com/formResponse?formkey="
                + getFormId() + "&amp;ifq");
    }

    /**
     * Implement this method by returning a String containing the id of a valid
     * GoogleDocs Form.
     * 
     * @return The Id of your GoogleDoc Form generated by importing ACRA's
     *         spreadsheet template.
     */
    public abstract String getFormId();

}
