name: deploy-docs

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_run:
    workflows: ["upload-javadoc"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build docs
        run: cd web && yarn install && yarn run build
      - name: Commit and push changes
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: 'ACRA/acra.github.com'
          publish_branch: 'master'
          publish_dir: ./web/build/
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          full_commit_message: "Update docs from ${{ github.sha }}"